import "package:get/get.dart";

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "couldNotFetchDoctors": "Could Not Fetch Doctors",
          "noDoctorsAvailable": "No Doctors Available",
          "someThingWentWrong": "Something went wrong",
          "noPaymentsFound": "No Payment Method Found",
          "DoYouwantToExit": "Do you want to exit the app",
          "ExitApp": "Exit App",
          "noWorkLocationsFound": "No Work Locations Found",
          "noDiagnosticsSelected": "No Diagnostics Selected",
          "familyMember": "Family Member",
          "noSessions": "No Sessions",
          "welcometo": "Welcome To",
          "takecareof": "Take Care Of",
          "yourhealth": "Your Health!",
          "manageYourHealth": "Manage your health with us",
          "with": "With",
          "goodmorning": "GOOD MORNING",
          "goodEvening": "GOOD EVENING",
          "goodNight": "GOOD NIGHT",
          "goodAfterNoon": "GOOD AFTERNOON",
          "onlineOffline": "Online & Offline ",
          "consultations": "Consultations",
          "booknow": "Book Now",
          "selectservices": "Select Services",
          "homeSample": "Home Sample",
          "imageBooking": "Image Booking",
          "imagingbooking": "Imaging Booking",
          "doctorConsultation": "Doctor Consultation",
          "reports": "Reports",
          "healthSummary": "Health Summary",
          "healthAnalysis": "Health Analysis",
          "todayAvailable": "Today Available",
          "generalConsultation": "General Consultation",
          "getAppointment": "Get Appointment",
          "consultatclinic": "Consult at Clinic",
          "home": "Home",
          "profile": "Profile",
          "schedule": "Schedule",
          "help": "Help",
          "helpful": "Helpful",
          "helpfull": "Helpful",
          "history": "History",
          "familyMembers": "Family Members",
          "location": "Location",
          "wallet": "Wallet",
          "packages": "Package Record",
          "forgotPassword": "Forgot Password?",
          "biometric": "Biometric",
          "privacyPolicy": "Privacy Policy",
          "termsAndConditions": "Terms & Conditions",
          "logout": "logout",
          "labInvestions": "Lab Investigations",
          "selectTest": "Select Test",
          "description": "Description",
          "address": "Address",
          "paymentMethod": "Payment Gateway",
          "prescribedBy": "Prescribed By",
          "self": "Self",
          "doctor": "Doctor",
          "outdoorDoctor": "Outdoor Doctor",
          "select Doctor": "Select Doctor",
          "summary": "Summary",
          "datehour": "Date & Hour",
          "package": "Package",
          "test": "Test",
          "price": "Price",
          "grandTotal": "Grand Total",
          "appointmentConfirm": "Book Appointment",
          "attachPrescription": "Attach Prescription",
          "login": "LOGIN",
          "Login": "Login",
          "donthaveanAccount": "Don't have an Account",
          "register": "Register",
          "registerNow": "Register Now",
          "fullName": "Full Name",
          "yourMobNumber": "Your Mobile Number",
          "email": "Email",
          "dateOfBirth": "Date of Birth",
          "gender": "Gender",
          "password": "Password",
          "retypePassword": " Re-type Password",
          "country": "Country",
          "state": "State",
          "city": "City",
          "street": "Street",
          "alreadyHaveAnAccount": "Already have an account?",
          "signin": "Sign in",
          "registered": "Registered",
          "registrationCompleted":
              "Registration has been Successfully Completed",
          "ok": "OK",
          "payfromYourWallet": "Pay from your Wallet",
          "payOnline": "Pay Online",
          "payAtClinic": "Pay At Clinic",
          "congratulations": "Congratulations",
          "myAppointments": "My Appointments",
          "bookyourAppointments": "Book your Appointment",
          "searchDoctor": "Search Doctor",
          "patients": "Patients",
          "yearExperience": "Years of Experience",
          "rating": "Rating",
          "reviews": "Reviews",
          "descriptions": "Descriptions",
          "workingTime": "Working Time",
          "online&Clinic": "Online & Home Consultation Charges",
          "bookAppointment": "Book Appointment",
          "welcomeTo": "Welcome to",
          "username": "Username",
          "oopsFailed": "Oops, Failed",
          "appointmentFailed": "Appointment Failed",
          "checkInternet":
              "Please Check your Internet Connection And Try again",
          "appointmentBooked": "Appointment Booked Successfully",
          "viewAppointment": "View Appointment",
          "cancel": "Cancel",
          "glucose": "Glucose",
          "bloodPressure": "Blood Pressure values",
          "measurements": "Measurements",
          "connect": "Connect",
          "pulse": "Pulse",
          "temperature": "Temperature",
          "labTestResult": "Lab Test Result",
          "status": "Status",
          "pending": "Pending",
          "allergies": "Allergies",
          "addGlucose": "Add Glucose",
          "normal": "Normal",
          "fasting": "Fasting",
          "values": "Values",
          "condition": "Condition",
          "saveRecord": "Save Record",
          "calculate": "Calculate",
          "bmiCalculator": "BMI Calculator",
          "BMI": "BMI",
          "glucoseLevelMonitor": "Glucose Level Monitor",
          "enterValue": "Enter Value",
          "goodAfternoon": "GOOD AFTERNOON",
          "collectLocationData":
              "SIDRA Patient Care collects Location data to enable Home Sampling Services even when is closed or not in use",
          "permissions": "Permissions",
          "deleteAccount": "Delete Account",
          "languages": "Languages",
          "identityNumber": "National ID",
          "signup": "Sign up",
          "bpm": "BPM",
          "date": "Date",
          "time": "Time",
          "searchForSpecialities": "Search For Specialities",
          "specialities": "Specialities",
          "consultNow": "Consult Online",
          "specialists": "Specialists",
          "upcomingAppointments": "Upcoming Appointments",
          "dateAndTime": "Date and Time",
          "reschedule": "Reschedule",
          "onlineConsultation": "Online Consultation",
          "information1":
              "Our system and apps are mainly targeting Health Care and medical. We are collecting some other information and permissions in our apps to improve user experience and app functionality. The information we collect is ephemerally processed i.e. it is only used to start some service or functionality involved inside the application and not used after it is stopped. Some important one are mentioned below with prominent disclosure/reasons for collection",
          "information2":
              "Location: In order to show nearby doctors, app needs to get this permission from user. By enabling Location-Based services on your device, you agree and acknowledge  that (a) device data that is collected from you is directly relevant to your use of the App, (b) We may provide Location-Based services related to and based on your then-current location, and (c) We may use any information collected in connection with its provision of the App.For video calling between doctor and patient.For audio calling  between doctor and patient (a)User/Patient can upload profile picture (b) User/Patient can upload health records and files for doctor to examine (c)User/Patient can download and view reports etc.",
          "usage":
              "We use the informative we collect in various ways, including to: (a)Provide, operate, and maintain our services and products (b)Understand and analyze how you use our services and products (c)Develop new product, services features, and functionality (d) Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes (e) Send your emails (f) Find and prevent fraud.",
          "disclosure":
              "We may disclose personal information to any person performing audit, legal, operational or other services for us. We will use information which does not identify the individual for these activities whenever reasonably possible. Under the CCPA, among other rights, California consumers have the  right to Request that a business that collects personal data disclose the categories and specific pieces of personal data that a business has collected about consumers, Request that a business delete any personal data, not sell the consumers personal data. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer supportUnder the GDPR Data Protection Rights, every user is entitled to the right to request copies of your personal data. We may charge you a small fell for the service, right to request that we correct any information you believe in inaccurate, right to request that we erase your personal data, restrict its processing, object to our processing of your personal, transfer the data that we have collected to another organization or directly to you data under certain conditions. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer support",
          "consent":
              "By using our website, services & products, you hereby consent to our Privacy Policy and agree to its terms. If you are a doctor or medical professional registering on this App, by enrolling in or using this service, you hereby confirm that usage is at your own risk and you release and agree to hold harmless the providers, developers, deployers from liability for adverse consequences, including but limited to claims, actions or legal proceedings by third parties, loss or breach of any private data and/or damages suffered as a result thereof.",
          "consentTitle": "Consent",
          "usageTitle": "Usage",
          "disclosureTitle": "Disclosure",
          "informationWeCollect": "Information we Collect",
          "iHaveRead": "I have read and understand",
          "theTermsAndCondition": " the Terms and Conditions",
          "accept": "Accept",
          "decline": "Decline",
          "height": "Height",
          "weight": "Weight",
          "add": "Add",
          "servicesHome": "Services (Home)",
          "teleConsultation": "Tele Consultation",
          "diagnostics": "Diagnostics",
          "physio": "Physio",
          "nursing": "Nursing",
          "caregiver": "Caregiver",
          "respiratoryTherapy": "Respiratory Therapy",
          "dietitian": "Dietitian",
          "serviceSelected": "Service Selected",
          "collectesData":
              "collects Location data to enable  Services Home even when is closed or not in use",
          "agree": "Agree",
          "appointmentNotes": "Appointment Notes",
          "deny": "Deny",
          "search": "Search",
          "homeVisit": "Home Visit",
          "online": "Online",
          "subTotal": "Sub Total",
          "minFee": "Min. Fee",
          "doctorSchedule": "Doctor Schedule",
          "fee": "Fee",
          "charges": "Charges",
          "selectAddress": "Select Address",
          "selectLocation": "Select Location",
          "goodMorning": "GOOD MORNING",
          "token": "Token",
          "ecg": "ECG",
          "selectLanguage": "Select Language",
          "english": "English",
          "arabic": "Arabic",
          "hour": "Hour",
          "homeService": "Home Care Service",
          "labInvestigationBooking": "Lab Investigation Booking",
          "experience": "Experience",
          "paying": "Paying",
          "serviceBooked": "Service Booked Successfully.",
          "appointmentSuccessful":
              "Appointment Successfully Booked. You Will receive a notification",
          "failedAppointment":
              "Appointment failed please check your internet connection then try again.",
          "favorites": "Favourite",
          "noFavorites": "No Favorite Doctors Added",
          "contact": "Contact no.",
          "province/state": "Province/State",
          "editProfile": "Edit Profile",
          "update": "Update",
          "healthanalysis": "Health Analysis",
          "herearesomehealth": "Here are some Health facts about ",
          "men": "Men",
          "In": "in",
          "dubai": "Dubai, UAE ",
          "doctorName": "Doctor Name",
          "careGivers": "Caregiver",
          "disclaimer": "Disclaimer",
          "services": "Services",
          "go": "Go",
          "imaging": "Imaging Booking",
          "caretocure": "FROM CARE TO CURE",
          "forgotpassword": "Forgot Password ?",
          "ithappens":
              "It happen, kindly enter the email associated with your account",
          "createpassword": "Create New Password",
          "kindlyenter": "Kindly enter a unique password",
          "oldpaasword": "Old Password",
          "confirmpassword": "Confirm Password",
          "changepassword": "Change Password",
          "imagingTitle": "Imaging",
          "completed": "Completed",
          "upcoming": "Upcoming",
          "cancelled": "Cancelled",
          "noDataFound": "No data Found!",
          "service": "Service",
          "homeServices": "Home Services",
          "changePassword": "Change Password",
          "modeOfPayment": "Mode Of Payment",
          "digitalPrescriptions": "Digital Prescriptions",
          "otherReports": "Other Reports",
          "visitNo": "Visit Number",
          "checkInTime": "Check in Time",
          "visitTime": "Visit Time",
          "medicine": "Medicine",
          "dos": "DOS",
          "freq": "Freq",
          "duration": "Duration",
          "requested": "Requested",
          "all": "All",
          "connectFamilyMember": "Connect Family Member",
          "addFamilyMember": "Add Family Member",
          "personalInformation": "Personal Information",
          "firstName": "lastName",
          "fathersName": "Father Name",
          "phoneNumber": "Phone Number",
          "relation": "Relation",
          "martialStatus": "Marital Status",
          "bloodGroup": "Blood Group",
          "relationShip": "Relation",
          "selectGender": "       Select Gender",
          "selectMartialStatus": "Select Marital Status",
          "selectBloodGroup": "Select Blood Group",
          "firstNameRequired": "First Name Required",
          "lastNameIsRequired": "Last Name is Required",
          "identityNumberIsRequired": "National ID is Required",
          "recordFound": "Record Found",
          "registrationDate": "Registration Date",
          "age": "Age",
          "id": "ID",
          "documentsProof": "DocumentsProof",
          "report": "Report",
          "prescription": "Prescription",
          "invoice": "Invoice",
          "refund": "Refund",
          "amount": "Amount:",
          "addFamilyMembers": "Add Family Member",
          "changeLocation": "Change Location",
          "offline": "Offline",
          "atClinic": "Home Visit",
          "thisFieldIsRequired": "This Field is required",
          "doctorDidNotPrescribe": "Doctor did not prescribe any medicines yet",
          "noLabInvestigationsFound": "No Lab Investigations Found",
          "getTested": "Get Tested",
          "noDiagnostics": "No Diagnostics Available To Test",
          "year": "Years",
          "notifications": "Notification",
          "norecordfound": "No Record Found",
          "noservices": "No Services are selected",
          "noservicespackages": "No Services or Packages are selected",
          "noaddress": "Address Not Selected",
          "nopaymentmethod": "Payment Method not selected",
          "thisdatetime":
              "This Date and time is before the current Time. Please try again",
          "bloodpressure": "Blood Pressure",
          "bloodpressuremoniter": "Blood Pressure Monitor",
          "servicealreadyselected": "Service Already Selected",
          "labtestalreadyselected": "Lab Test Already Selected",
          "labtestpresent": "Lab Test Already Present in Selected Packages",
          "pleasetryagain": "Please Try Again",
          "bookingfailed": "Booking Failed, Please try again",
          "allrecordsfetched": "All records are fetched!",
          "labpackagealready": "Lab Package Already Selected",
          "someerroroccured": "Some Error Occured",
          "fillallfields": "Fill all the fields and add your profile picture",
          "passwordnotchanged": "Password not changed",
          "passandconfirmpass": "Password and Confirm Password doesn't match",
          "youarenotloggedin": "You are not logged in",
          "doctorofflice": "Doctor is Offline",
          "codesent": "Code has been sent",
          "somethingwentwrong": "Something went wrong!",
          "passwordchanged": "Password Changed",
          "coderror": "Code error",
          "successfullyupdated": "Successfully Update",
          "failedtoupated": "Failed to update ",
          "notfound": "Not Found",
          "notestsselected": "No Tests Selected",
          "pleaseloginfirst": "Please log in First",
          "samplesfromhome": "Samples from Home",
          "samplesinlab": "Samples in Lab",
          "province": "Province",
          "consultnow": "Consult Online",
          "homesampling": "Home Sampling",
          "selectdatetime": "Select Date & Time",
          "selecttime": "Time",
          "enterverificationcode": "Enter Verification Code",
          "entervericationsent":
              "Enter Verification Code Send to your email or Phone Number",
          "confirm": "Confirm",
          "doctoriscalling": "Doctor is Calling...",
          "waitingfordoctor": "Waiting for Doctor...",
          "minutes": "Minutes",
          "estimatedtime": "Estimated Time...",
          "patientname": "Patient Name",
          "patient": "Patient",
          "paymentmethod": "Payment Method",
          "scheduledappointment": "Scheduled Appointment",
          "patientinfo": "Patient Information",
          "paid": "Paid",
          "yourrelation": "Your Relation",
          "entercode": "Enter Code",
          "kindlyenterthecode":
              "Kindly enter the code sent to your email address",
          "healthanalysistools": "Health Analysis Tools",
          "feet": "Feet",
          "inch": "Inch",
          "calculatebmi": "Calculate BMI",
          "weightkg": "Weight (Kg)",
          "heightcm": "Height (cm)",
          "datetime": "Date/Time",
          "high": "High",
          "entersystolic": "Enter systolic / Upper BP",
          "enterlowerbp": "Enter systolic / Upper BP",
          "savebp": "Save BP",
          "glucosemoniter": "Glocuse Level Monitor",
          "glocuselevel": "Glocuse Level",
          "systolicupper": "Systolic (Upper)",
          "diastolic": "Diastolic (Lower)",
          "apptno": "Appt No.",
          "report/desc": "Report / Prescription",
          "discount": "Discount",
          "packagename": "Package Name",
          "pdfnotavail": "PDF not available",
          "selectcountry": "Please Select Country",
          "selectprovince": "Please Select Province",
          "selectcity": "Please Select City",
          "echo": "Echo",
          "selectdate": "Select Date",
          "day": "Day",
          "sunday": "Sunday",
          "recenttrans": "Recent Transections",
          "onlineconsultancy": "Online Consultancy",
          "loading": "Loading....",
          "timer": "Time",
          "nationalID": "Enter your National ID",
          "comingsoon": "Coming Soon",
          "termsofuse": "TERMS OF USE",
          "link":
              "The iHealthCure website located at https://ihealthcure.com/ is a copyrighted work belonging to iHealthCure. Certain features of the Site may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such features.",
          "access": "ACCESS TO THE SITE",
          "accessinformation":
              "Subject to these Terms. Company grants you a non-transferable, non-exclusive, revocable, limited license to access the Site solely for your own personal, noncommercial use.\n \n Certain Restrictions. The rights approved to you in these Terms are subject to the following restrictions: (a) you shall not sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site; (b) you shall not change, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms. All copyright and other proprietary notices on the Site must be retained on all copies thereof",
          "disclaimer1":
              "The site is provided on an \"as-is\" and \"as available\" basis, and company and our suppliers expressly disclaim any and all warranties and conditions of any kind, whether express, implied, or statutory, including all warranties or conditions of merchantability, fitness for a particular purpose, title, quiet enjoyment, accuracy, or non-infringement. We and our suppliers make not guarantee that the site will meet your requirements, will be available on an uninterrupted, timely, secure, or error-free basis, or will be accurate, reliable, free of viruses or other harmful code, complete, legal, or safe. If applicable law requires any warranties with respect to the site, all such warranties are limited in duration to ninety (90) days from the date of first use.",
          "disclaimertitle": "DISCLAIMERS",
          "contactinfo": "CONTACT INFORMATION",
          "contactinfodetail":
              "Address: Office # 3, 2nd Floor Gul Arcade Main Commercial Area Chaklala Scheme-3 Rawalpindi (Pakistan)\n\nEmail: info@iHealthCure.com",
          "selectMaritalStatus": "Marital Status",
          "loginsuccess": "Logged in successfully",
          "no": "No",
          "yes": "Yes",
          "selectTime": "Select Time",
          "enterYourNationalId": "Enter your National ID",
          "passwordIsEmpty": "Password field is Empty",
          "enterEmail": "Enter Your Email",
          "verifyCode": "Verify Code",
          "enterYourFullName": "Enter your full name",
          "enteryourPhoneNumber": "Enter your Phone Number",
          "enterAvalidEmail": "Enter a valid email",
          "enterDateOfBirth": "Enter Your Date of Birth",
          "enterYourPassword": "EnterYourPassword",
          "enterConfirmPassword": "Confirm Password before Proceeding",
          "selectCountry": "Select Country",
          "selectProvince": "Select Province",
          "selectCity": "Select City",
          "enterYourAddress": "Enter your address",
          "confirmPassword": "Confirm Password"
        },
        "ar_SA": {
          "confirmPassword": "تأكيد كلمة المرور",
          "enterYourNationalId": "أدخل رقم الهوية الوطنية الخاص بك",
          "passwordIsEmpty": "حقل كلمة المرور فارغ",
          "enterEmail": "أدخل بريدك الإلكتروني",
          "verifyCode": "التحقق من كود",
          "enterYourFullName": "أدخل اسمك الكامل",
          "enteryourPhoneNumber": "أدخل رقم هاتفك",
          "enterAvalidEmail": "أدخل بريد إلكتروني متاح",
          "enterDateOfBirth": "أدخل تاريخ ميلادك",
          "enterYourPassword": "ادخل رقمك السري",
          "enterConfirmPassword": "تأكيد كلمة المرور قبل المتابعة",
          "selectCountry": "حدد الدولة",
          "selectProvince": "اختر المقاطعة",
          "selectCity": "اختر مدينة",
          "enterYourAddress": "أدخل عنوانك",
          "selectTime": "حدد الوقت",
          "couldNotFetchDoctors": "تعذر جلب الأطباء",
          "noDoctorsAvailable": "لم يتم العثور على أطباء",
          "someThingWentWrong": "هناك خطأ ما",
          "noPaymentsFound": "لم يتم العثور على طريقة الدفع",
          "yes": "نعم",
          "no": "لا",
          "DoYouwantToExit": "هل تريد الخروج من التطبيق",
          "ExitApp": "الخروج من التطبيق",
          "noWorkLocationsFound": "لم يتم العثور على مواقع العمل",
          "noDiagnosticsSelected": "لم يتم تحديد أي تشخيصات",
          "loginsuccess": "تم تسجيل الدخول بنجاح",
          "familyMember": "عضو الأسرة",
          "selectMaritalStatus": "الحالة الاجتماعية",
          "noSessions": "لا جلسات",
          "welcometo": "مرحبا بك في",
          "takecareof": "رعاية",
          "yourhealth": "صحتك!",
          "manageYourHealth": "إدارة صحتك معنا",
          "with": "مع",
          "goodmorning": "صباح الخير",
          "goodEvening": "مساء الخير",
          "goodNight": "طاب مساؤك",
          "goodAfterNoon": "مساء الخير",
          "onlineOffline": "متصل ",
          "consultations": "استشارات",
          "booknow": "احجز الآن",
          "selectservices": "حدد الخدمات",
          "homeSample": "عينة المنزل",
          "imageBooking": "حجز الصور",
          "imagingbooking": "حجز التصوير",
          "doctorConsultation": "استشارة الطبيب",
          "reports": "التقارير",
          "healthSummary": "ملخص الصحة",
          "healthAnalysis": "تحليل الصحة",
          "todayAvailable": "متوفر اليوم",
          "generalConsultation": "الاستشارة العامة",
          "getAppointment": "احصل على موعد",
          "consultatclinic": "استشارة في العيادة",
          "home": "بيت",
          "profile": "حساب تعريفي",
          "schedule": "جدول",
          "help": "يساعد",
          "helpful": "متعاون",
          "helpfull": "متعاون",
          "history": "تاريخ",
          "familyMembers": "أفراد الأسرة",
          "location": "موقع",
          "wallet": "محفظة",
          "packages": "سجل الحزمة",
          "forgotPassword": "هل نسيت كلمة السر؟",
          "biometric": "بصمات",
          "privacyPolicy": "سياسة الخصوصية",
          "termsAndConditions": "شروط",
          "logout": "تسجيل خروج",
          "labInvestions": "التحقيقات المخبرية",
          "selectTest": "حدد اختبار",
          "description": "وصف",
          "address": "عنوان",
          "paymentMethod": "بوابة الدفع",
          "prescribedBy": "المنصوص عليها",
          "self": "الذات",
          "doctor": "طبيب",
          "outdoorDoctor": "طبيب خارجي",
          "select Doctor": "اختر الطبيب",
          "summary": "ملخص",
          "datehour": "تاريخ",
          "package": "طَرد",
          "test": "امتحان",
          "price": "سعر",
          "grandTotal": "المجموع الإجمالي",
          "appointmentConfirm": "موعد الكتاب",
          "attachPrescription": "إرفاق وصفة طبية",
          "login": "تسجيل الدخول",
          "Login": "تسجيل الدخول",
          "donthaveanAccount": "ليس لديك حساب",
          "register": "يسجل",
          "registerNow": "سجل الان",
          "fullName": "الاسم الكامل",
          "yourMobNumber": "رقم هاتفك",
          "email": "بريد إلكتروني",
          "dateOfBirth": "تاريخ الميلاد",
          "gender": "جنس",
          "password": "كلمة المرور",
          "retypePassword": " أعد إدخال كلمة السر",
          "country": "دولة",
          "state": "ولاية",
          "city": "مدينة",
          "street": "شارع",
          "alreadyHaveAnAccount": "هل لديك حساب؟",
          "signin": "تسجيل الدخول",
          "registered": "مسجل",
          "registrationCompleted": "تم التسجيل بنجاح",
          "ok": "نعم",
          "payfromYourWallet": "ادفع من محفظتك",
          "payOnline": "ادفع عبر الإنترنت",
          "payAtClinic": "الدفع في العيادة",
          "congratulations": "تهانينا",
          "myAppointments": "مواعيدي",
          "bookyourAppointments": "احجز موعدك",
          "searchDoctor": "بحث دكتور",
          "patients": "مرضى",
          "yearExperience": "سنوات من الخبرة",
          "rating": "تقييم",
          "reviews": "التعليقات",
          "descriptions": "الأوصاف",
          "workingTime": "وقت العمل",
          "online&Clinic": "متصل",
          "bookAppointment": "موعد الكتاب",
          "welcomeTo": "مرحبا بك في",
          "username": "اسم المستخدم",
          "oopsFailed": "عفوًا، فشل",
          "appointmentFailed": "فشل الموعد",
          "checkInternet": "الرجاء التحقق من اتصالك بالإنترنت وحاول مرة أخرى",
          "appointmentBooked": "تم حجز الموعد بنجاح",
          "viewAppointment": "عرض الموعد",
          "cancel": "يلغي",
          "glucose": "الجلوكوز",
          "bloodPressure": "قيم ضغط الدم",
          "measurements": "قياسات",
          "connect": "يتصل",
          "pulse": "نبض",
          "temperature": "درجة حرارة",
          "labTestResult": "نتيجة الاختبار المعملي",
          "status": "حالة",
          "pending": "قيد الانتظار",
          "allergies": "الحساسية",
          "addGlucose": "أضف الجلوكوز",
          "normal": "طبيعي",
          "fasting": "صيام",
          "values": "قيم",
          "condition": "حالة",
          "saveRecord": "حفظ السجل",
          "calculate": "احسب",
          "bmiCalculator": "حاسبة مؤشر كتلة الجسم",
          "BMI": "مؤشر كتلة الجسم",
          "glucoseLevelMonitor": "مراقب مستوى الجلوكوز",
          "enterValue": "أدخل القيمة",
          "goodAfternoon": "مساء الخير",
          "collectLocationData":
              "تقوم SIDRA Patient Care بجمع بيانات الموقع لتمكين خدمات أخذ العينات المنزلية حتى عندما تكون مغلقة أو غير مستخدمة",
          "permissions": "الأذونات",
          "deleteAccount": "حذف الحساب",
          "languages": "اللغات",
          "identityNumber": "الهوية الوطنية",
          "signup": "اشتراك",
          "bpm": "بي بي إم",
          "date": "تاريخ",
          "time": "وقت",
          "searchForSpecialities": "البحث عن المتخصصين",
          "specialities": "التخصصات",
          "consultNow": "استشر عبر الإنترنت",
          "specialists": "المتخصصين",
          "upcomingAppointments": "المواعيد القادمة",
          "dateAndTime": "التاريخ و الوقت",
          "reschedule": "إعادة جدولة",
          "onlineConsultation": "التشاور عبر الإنترنت",
          "information1":
              "يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. ",
          "information2":
              "الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. ",
          "usage":
              "نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و ",
          "disclosure":
              "يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. ",
          "consent": "من خلال استخدام موقعنا وخدماتنا",
          "consentTitle": "موافقة",
          "usageTitle": "الاستخدام",
          "disclosureTitle": "إفشاء",
          "informationWeCollect": "المعلومات التي نجمعها",
          "iHaveRead": "لقد قرأت وفهمت",
          "theTermsAndCondition": " الشروط والأحكام",
          "accept": "يقبل",
          "decline": "انخفاض",
          "height": "ارتفاع",
          "weight": "وزن",
          "add": "يضيف",
          "servicesHome": "الخدمات (المنزلية)",
          "teleConsultation": "استشارة عن بعد",
          "diagnostics": "التشخيص",
          "physio": "العلاج الطبيعي",
          "nursing": "التمريض",
          "caregiver": "الراعي",
          "respiratoryTherapy": "العلاج التنفسي",
          "dietitian": "اخصائي تغذيه",
          "serviceSelected": "الخدمة مختارة",
          "collectesData":
              "يجمع بيانات الموقع لتمكين صفحة الخدمات الرئيسية حتى عندما تكون مغلقة أو غير مستخدمة",
          "agree": "يوافق",
          "appointmentNotes": "ملاحظات التعيين",
          "deny": "ينكر",
          "search": "يبحث",
          "homeVisit": "زيارة منزلية",
          "online": "متصل",
          "subTotal": "المجموع الفرعي",
          "minFee": "دقيقة. ",
          "doctorSchedule": "جدول الطبيب",
          "fee": "مصاريف",
          "charges": "رسوم",
          "selectAddress": "حدد العنوان",
          "selectLocation": "اختر موقعا",
          "goodMorning": "صباح الخير",
          "token": "رمز مميز",
          "ecg": "تخطيط كهربية القلب",
          "selectLanguage": "اختار اللغة",
          "english": "إنجليزي",
          "arabic": "عربي",
          "hour": "ساعة",
          "homeService": "خدمة الرعاية المنزلية",
          "labInvestigationBooking": "حجز الفحوصات المخبرية",
          "experience": "خبرة",
          "paying": "الدفع",
          "serviceBooked": "تم حجز الخدمة بنجاح.",
          "appointmentSuccessful": "تم حجز الموعد بنجاح. ",
          "failedAppointment":
              "فشل الموعد، يرجى التحقق من اتصالك بالإنترنت ثم حاول مرة أخرى.",
          "favorites": "المفضلة",
          "noFavorites": "لم تتم إضافة أي الأطباء المفضلين",
          "contact": "رقم الاتصال.",
          "province/state": "المقاطعة/الولاية",
          "editProfile": "تعديل الملف الشخصي",
          "update": "تحديث",
          "healthanalysis": "تحليل الصحة",
          "herearesomehealth": "فيما يلي بعض الحقائق الصحية حول ",
          "men": "رجال",
          "In": "في",
          "dubai": "دبي الامارات العربية المتحدة ",
          "doctorName": "اسم الطبيب",
          "careGivers": "الراعي",
          "disclaimer": "تنصل",
          "services": "خدمات",
          "go": "يذهب",
          "imaging": "حجز التصوير",
          "caretocure": "من الرعاية إلى العلاج",
          "forgotpassword": "هل نسيت كلمة السر ؟",
          "ithappens":
              "إذا حدث ذلك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك",
          "createpassword": "إنشاء كلمة مرور جديدة",
          "kindlyenter": "يرجى إدخال كلمة مرور فريدة",
          "oldpaasword": "كلمة المرور القديمة",
          "confirmpassword": "تأكيد كلمة المرور",
          "changepassword": "تغيير كلمة المرور",
          "imagingTitle": "التصوير",
          "completed": "مكتمل",
          "upcoming": "القادمة",
          "cancelled": "ألغيت",
          "noDataFound": "لاتوجد بيانات!",
          "service": "خدمة",
          "homeServices": "خدمات منزلية",
          "changePassword": "تغيير كلمة المرور",
          "modeOfPayment": "طريقة الدفع",
          "digitalPrescriptions": "الوصفات الطبية الرقمية",
          "otherReports": "تقارير أخرى",
          "visitNo": "رقم الزيارة",
          "checkInTime": "تحقق في الوقت المناسب",
          "visitTime": "وقت الزيارة",
          "medicine": "الدواء",
          "dos": "دوس",
          "freq": "التكرار",
          "duration": "مدة",
          "requested": "مطلوب",
          "all": "الجميع",
          "connectFamilyMember": "ربط أفراد العائلة",
          "addFamilyMember": "إضافة فرد من العائلة",
          "personalInformation": "معلومات شخصية",
          "firstName": "اسم العائلة",
          "fathersName": "اسم الاب ",
          "phoneNumber": "رقم التليفون",
          "relation": "علاقة",
          "martialStatus": "الحالة الإجتماعية",
          "bloodGroup": "فصيلة الدم",
          "relationShip": "علاقة",
          "selectGender": "حدد نوع الجنس",
          "selectMartialStatus": "حدد الحالة العسكرية",
          "selectBloodGroup": "حدد فصيلة الدم",
          "firstNameRequired": "الاسم الأول مطلوب",
          "lastNameIsRequired": "إسم العائلة مطلوب",
          "identityNumberIsRequired": "مطلوب الهوية الوطنية",
          "recordFound": "تم العثور على السجل",
          "registrationDate": "تاريخ التسجيل",
          "age": "عمر",
          "id": "بطاقة تعريف",
          "documentsProof": "DocumentsProof",
          "report": "تقرير",
          "prescription": "روشتة",
          "invoice": "فاتورة",
          "refund": "استرداد",
          "amount": "كمية:",
          "addFamilyMembers": "إضافة أفراد العائلة",
          "changeLocation": "تغيير الموقع",
          "offline": "غير متصل على الانترنت",
          "atClinic": "زيارة منزلية",
          "thisFieldIsRequired": "هذه الخانة مطلوبه",
          "doctorDidNotPrescribe": "الطبيب لم يصف أي دواء بعد",
          "noLabInvestigationsFound": "لم يتم العثور على تحقيقات معملية",
          "getTested": "الحصول على اختبار",
          "noDiagnostics": "لا توجد تشخيصات متاحة للاختبار",
          "year": "سنين",
          "notifications": "إشعارات",
          "norecordfound": "لا يوجد سجلات",
          "noservices": "لم يتم تحديد أي خدمات",
          "noservicespackages": "لم يتم تحديد أي خدمات أو حزم",
          "noaddress": "العنوان غير محدد",
          "nopaymentmethod": "لم يتم تحديد طريقة الدفع",
          "thisdatetime": "هذا التاريخ والوقت يسبق الوقت الحالي. ",
          "bloodpressure": "ضغط الدم",
          "bloodpressuremoniter": "جهاز قياس ضغط الدم",
          "servicealreadyselected": "الخدمة مختارة بالفعل",
          "labtestalreadyselected": "تم تحديد الاختبار المعملي بالفعل",
          "labtestpresent": "الاختبار المعملي موجود بالفعل في الحزم المحددة",
          "pleasetryagain": "حاول مرة اخرى",
          "bookingfailed": "فشل الحجز، يرجى المحاولة مرة أخرى",
          "allrecordsfetched": "يتم جلب كافة السجلات!",
          "labpackagealready": "تم تحديد حزمة المختبر بالفعل",
          "someerroroccured": "حدث بعض الخطأ",
          "fillallfields": "املأ جميع الحقول وأضف صورتك الشخصية",
          "passwordnotchanged": "كلمة المرور لم تتغير",
          "passandconfirmpass": "كلمة المرور وتأكيد كلمة المرور غير متطابقين",
          "youarenotloggedin": "لم يتم دخولك",
          "doctorofflice": "الطبيب غير متصل",
          "codesent": "تم إرسال الرمز",
          "somethingwentwrong": "هناك خطأ ما!",
          "passwordchanged": "تم تغيير كلمة السر",
          "coderror": "رمز الخطأ",
          "successfullyupdated": "تم التحديث بنجاح",
          "failedtoupated": "اخفاق التحديث ",
          "notfound": "غير معثور عليه",
          "notestsselected": "لم يتم تحديد أي اختبارات",
          "pleaseloginfirst": "الرجاء تسجيل الدخول أولا",
          "samplesfromhome": "عينات من المنزل",
          "samplesinlab": "العينات في المختبر",
          "province": "مقاطعة",
          "consultnow": "استشر عبر الإنترنت",
          "homesampling": "أخذ العينات المنزلية",
          "selectdatetime": "حدد تاريخ",
          "selecttime": "وقت",
          "enterverificationcode": "أدخل رمز التحقق",
          "entervericationsent":
              "أدخل رمز التحقق أرسل إلى بريدك الإلكتروني أو رقم هاتفك",
          "confirm": "يتأكد",
          "doctoriscalling": "الطبيب يتصل...",
          "waitingfordoctor": "في انتظار الطبيب...",
          "minutes": "دقائق",
          "estimatedtime": "الوقت المقدر...",
          "patientname": "اسم المريض",
          "patient": "مريض",
          "paymentmethod": "طريقة الدفع او السداد",
          "scheduledappointment": "الموعد المقرر",
          "patientinfo": "معلومات المريض",
          "paid": "مدفوع",
          "yourrelation": "واقعك",
          "entercode": "ادخل الرمز",
          "kindlyenterthecode":
              "يرجى إدخال الرمز المرسل إلى عنوان بريدك الإلكتروني",
          "healthanalysistools": "أدوات التحليل الصحي",
          "feet": "قدم",
          "inch": "بوصة",
          "calculatebmi": "حساب مؤشر كتلة الجسم",
          "weightkg": "الوزن (كجم)",
          "heightcm": "الطول (سم)",
          "datetime": "التاريخ/الوقت",
          "high": "عالي",
          "entersystolic": "أدخل الضغط الانقباضي/العلوي",
          "enterlowerbp": "أدخل الضغط الانقباضي/العلوي",
          "savebp": "حفظ بريتيش بتروليوم",
          "glucosemoniter": "مراقبة مستوى الجلوكوز",
          "glocuselevel": "مستوى الجلوكوز",
          "systolicupper": "الانقباضي (العلوي)",
          "diastolic": "الانبساطي (السفلي)",
          "apptno": "رقم التطبيق",
          "report/desc": "تقرير / وصفة طبية",
          "discount": "تخفيض",
          "packagename": "اسم الحزمة",
          "pdfnotavail": "PDF غير متوفر",
          "selectcountry": "الرجاء تحديد البلد",
          "selectprovince": "الرجاء اختيار المقاطعة",
          "selectcity": "الرجاء اختيار المدينة",
          "echo": "صدى صوت",
          "selectdate": "حدد تاريخ",
          "day": "يوم",
          "sunday": "الأحد",
          "recenttrans": "التحويلات الأخيرة",
          "onlineconsultancy": "الاستشارة عبر الإنترنت",
          "loading": "تحميل....",
          "timer": "وقت",
          "nationalID": "أدخل رقم الهوية الوطنية الخاص بك",
          "comingsoon": "قريباً",
          "termsofuse": "شروط الاستخدام",
          "link":
              "موقع iHealthCure الموجود على https://ihealthcure.com/ هو عمل محمي بحقوق الطبع والنشر ينتمي إلى iHealthCure. قد تخضع بعض ميزات الموقع لإرشادات أو شروط أو قواعد إضافية، والتي سيتم نشرها على الموقع فيما يتعلق بهذه الميزات.",
          "access": "الوصول إلى الموقع",
          "accessinformation":
              "تخضع لهذه الشروط. تمنحك الشركة ترخيصًا محدودًا وغير قابل للتحويل وغير حصري وقابل للإلغاء للوصول إلى الموقع فقط لاستخدامك الشخصي وغير التجاري.\n \n قيود معينة. تخضع الحقوق المعتمدة لك في هذه الشروط للقيود التالية: (أ) لا يجوز لك بيع الموقع أو تأجيره أو استئجاره أو نقله أو التنازل عنه أو توزيعه أو استضافته أو استغلاله تجاريًا؛ (ب) لا يجوز لك تغيير أو عمل أعمال مشتقة أو تفكيك أو تجميع عكسي أو إجراء هندسة عكسية لأي جزء من الموقع؛ (ج) لا يجوز لك الوصول إلى الموقع من أجل إنشاء موقع ويب مماثل أو تنافسي؛ و (د) باستثناء ما هو منصوص عليه صراحةً هنا، لا يجوز نسخ أي جزء من الموقع أو إعادة إنتاجه أو توزيعه أو إعادة نشره أو تنزيله أو عرضه أو نشره أو نقله بأي شكل أو بأي وسيلة ما لم تتم الإشارة إلى خلاف ذلك، أي إصدار أو تحديث أو وتخضع الإضافات الأخرى إلى وظائف الموقع لهذه الشروط. يجب الاحتفاظ بجميع حقوق الطبع والنشر وإشعارات الملكية الأخرى الموجودة على الموقع على جميع نسخه",
          "disclaimer1":
              "يتم توفير الموقع على أساس كما هو كما هو متاح، وتتنصل الشركة وموردونا صراحةً من أي وجميع الضمانات والشروط من أي نوع، سواء كانت صريحة أو ضمنية أو قانونية، بما في ذلك جميع الضمانات. أو شروط القابلية للتسويق أو الملاءمة لغرض معين أو اللقب أو الاستمتاع الهادئ أو الدقة أو عدم الانتهاك. نحن وموردونا لا نضمن أن الموقع سوف يلبي متطلباتك، أو سيكون متاحًا دون انقطاع، أو في الوقت المناسب، أو آمنًا، أو خاليًا من الأخطاء، أو سيكون دقيقًا، وموثوقًا، وخاليًا من الفيروسات أو غيرها من الأكواد الضارة، وكاملًا، وقانونيًا. ، أو آمنة. إذا كان القانون المعمول به يتطلب أي ضمانات فيما يتعلق بالموقع، فإن جميع هذه الضمانات تقتصر مدتها على تسعين (90) يومًا من تاريخ الاستخدام الأول.",
          "disclaimertitle": "إخلاء المسؤولية",
          "contactinfo": "معلومات الاتصال",
          "contactinfodetail": "العنوان: المكتب"
        },
        "ur_PK": {
          "enterYourNationalId": "اپنی قومی شناخت درج کریں۔",
          "passwordIsEmpty": "پاس ورڈ فیلڈ خالی ہے۔",
          "enterEmail": "اپنا ای میل درج کریں۔",
          "verifyCode": "کوڈ کی تصدیق کریں",
          "enterYourFullName": "اپنا پورا نام درج کریں",
          "enteryourPhoneNumber": "اپنا فون نمبر درج کریں۔",
          "enterAvalidEmail": "ایک درست ای میل درج کریں۔",
          "enterDateOfBirth": "اپنی تاریخ پیدائش درج کریں۔",
          "enterYourPassword": "اپنا پاس ورڈ درج کریں",
          "enterConfirmPassword": "آگے بڑھنے سے پہلے پاس ورڈ کی تصدیق کریں۔",
          "selectCountry": "ملک کا انتخاب کیجئے",
          "selectProvince": "صوبہ منتخب کریں۔",
          "selectCity": "شہر منتخب کریں۔",
          "enterYourAddress": "اپنا پتہ درج کریں۔",
          "selectTime": "وقت منتخب کریں",
          "couldNotFetchDoctors": "ڈاکٹرز نہیں لا سکے۔",
          "noDoctorsAvailable": "کوئی ڈاکٹر نہیں ملا",
          "someThingWentWrong": "کچھ غلط ہو گیا",
          "noPaymentsFound": "ادائیگی کا کوئی طریقہ نہیں ملا",
          "yes": "جی ہاں",
          "no": "نہیں",
          "DoYouwantToExit": "کیا آپ ایپ سے باہر نکلنا چاہتے ہیں؟",
          "ExitApp": "ایپ سے باہر نکلیں۔",
          "noWorkLocationsFound": "کام کی کوئی جگہ نہیں ملی",
          "noDiagnosticsSelected": "کوئی تشخیصی طریقہ منتخب نہیں کیا گیا۔",
          "loginsuccess": "کامیابی سے لاگ ان ہو گیا۔",
          "familyMember": "خاندان کا رکن",
          "noSessions": "کوئی سیشن نہیں۔",
          "welcometo": "میں خوش آمدید",
          "takecareof": "کا خیال رکھنا",
          "yourhealth": "آپ کی صحت!",
          "manageYourHealth": "ہمارے ساتھ اپنی صحت کا انتظام کریں۔",
          "with": "کے ساتھ",
          "goodmorning": "صبح بخیر",
          "goodEvening": "شام بخیر",
          "goodNight": "شب بخیر",
          "goodAfterNoon": "دوپہر بخیر",
          "onlineOffline": "آن لائن ",
          "consultations": "مشاورت",
          "booknow": "ابھی بک کریں۔",
          "selectservices": "خدمات کو منتخب کریں۔",
          "homeSample": "گھر کا نمونہ",
          "imageBooking": "تصویری بکنگ",
          "imagingbooking": "امیجنگ بکنگ",
          "doctorConsultation": "ڈاکٹر کی مشاورت",
          "reports": "رپورٹس",
          "healthSummary": "صحت کا خلاصہ",
          "healthAnalysis": "صحت کا تجزیہ",
          "todayAvailable": "آج دستیاب ہے۔",
          "generalConsultation": "عمومی مشاورت",
          "getAppointment": "اپوائنٹمنٹ حاصل کریں۔",
          "consultatclinic": "کلینک میں مشورہ کریں۔",
          "home": "گھر",
          "profile": "پروفائل",
          "schedule": "شیڈول",
          "help": "مدد",
          "helpful": "مددگار",
          "helpfull": "مددگار",
          "history": "تاریخ",
          "familyMembers": "خاندان کے افراد",
          "location": "مقام",
          "wallet": "پرس",
          "packages": "پیکیج ریکارڈ",
          "forgotPassword": "پاسورڈ بھول گے؟",
          "biometric": "بائیو میٹرک",
          "privacyPolicy": "رازداری کی پالیسی",
          "termsAndConditions": "شرائط",
          "logout": "لاگ آوٹ",
          "labInvestions": "لیب کی تحقیقات",
          "selectTest": "ٹیسٹ کو منتخب کریں۔",
          "description": "تفصیل",
          "address": "پتہ",
          "paymentMethod": "پیسے ادا کرنے کا طریقہ",
          "prescribedBy": "کے ذریعہ تجویز کردہ",
          "self": "خود",
          "doctor": "ڈاکٹر",
          "outdoorDoctor": "آؤٹ ڈور ڈاکٹر",
          "select Doctor": "ڈاکٹر کا انتخاب کریں۔",
          "summary": "خلاصہ",
          "datehour": "تاریخ",
          "package": "پیکج",
          "test": "پرکھ",
          "price": "قیمت",
          "grandTotal": "مجموعی عدد",
          "appointmentConfirm": "بک اپائنٹمنٹ",
          "attachPrescription": "نسخہ منسلک کریں۔",
          "login": "لاگ ان کریں",
          "Login": "لاگ ان کریں",
          "donthaveanAccount": "اکاؤنٹ نہیں ہے۔",
          "register": "رجسٹر کریں۔",
          "registerNow": "ابھی رجسٹر کریں",
          "fullName": "پورا نام",
          "yourMobNumber": "آپ کا موبائل نمبر",
          "email": "ای میل",
          "dateOfBirth": "پیدائش کی تاریخ",
          "gender": "صنف",
          "password": "پاس ورڈ",
          "retypePassword": " دوبارہ پاسوورڈ لکھئے",
          "country": "ملک",
          "state": "حالت",
          "city": "شہر",
          "street": "گلی",
          "alreadyHaveAnAccount": "پہلے سے ہی اکاؤنٹ ہے؟",
          "signin": "سائن ان",
          "registered": "رجسٹرڈ",
          "registrationCompleted": "رجسٹریشن کامیابی سے مکمل ہو گئی ہے۔",
          "ok": "ٹھیک ہے",
          "payfromYourWallet": "اپنے والٹ سے ادائیگی کریں۔",
          "payOnline": "آن لائن ادائیگی کریں۔",
          "payAtClinic": "کلینک میں ادائیگی کریں۔",
          "congratulations": "مبارک ہو",
          "myAppointments": "میری اپائنٹمنٹس",
          "bookyourAppointments": "اپنی اپوائنٹمنٹ بک کرو",
          "searchDoctor": "ڈاکٹر کو تلاش کریں۔",
          "patients": "مریض",
          "yearExperience": "برسوں کا تجربہ",
          "rating": "درجہ بندی",
          "reviews": "جائزے",
          "descriptions": "تفصیل",
          "workingTime": "کام کرنے کا وقت",
          "online&Clinic": "آن لائن",
          "bookAppointment": "بک اپائنٹمنٹ",
          "welcomeTo": "میں خوش آمدید",
          "username": "صارف نام",
          "oopsFailed": "افوہ، ناکام",
          "appointmentFailed": "ملاقات ناکام ہو گئی۔",
          "checkInternet":
              "براہ کرم اپنا انٹرنیٹ کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
          "appointmentBooked": "ملاقات کامیابی سے بک گئی۔",
          "viewAppointment": "ملاقات کا وقت دیکھیں",
          "cancel": "منسوخ کریں۔",
          "glucose": "گلوکوز",
          "bloodPressure": "بلڈ پریشر کی اقدار",
          "measurements": "پیمائش",
          "connect": "جڑیں",
          "pulse": "نبض",
          "temperature": "درجہ حرارت",
          "labTestResult": "لیب ٹیسٹ کا نتیجہ",
          "status": "حالت",
          "pending": "زیر التواء",
          "allergies": "الرجی",
          "addGlucose": "گلوکوز شامل کریں۔",
          "normal": "نارمل",
          "fasting": "روزہ رکھنا",
          "values": "اقدار",
          "condition": "حالت",
          "saveRecord": "ریکارڈ محفوظ کریں۔",
          "calculate": "حساب لگانا",
          "bmiCalculator": "BMI کیلکولیٹر",
          "BMI": "BMI",
          "glucoseLevelMonitor": "گلوکوز لیول مانیٹر",
          "enterValue": "قدر درج کریں۔",
          "goodAfternoon": "دوپہر بخیر",
          "collectLocationData":
              "ہیلپ فل پیشنٹ کیئر ہوم سیمپلنگ سروسز کو فعال کرنے کے لیے لوکیشن ڈیٹا اکٹھا کرتا ہے یہاں تک کہ بند ہو یا استعمال میں نہ ہو۔",
          "permissions": "اجازتیں",
          "deleteAccount": "کھاتہ مٹا دو",
          "languages": "زبانیں",
          "identityNumber": "قومی شناختی",
          "signup": "سائن اپ",
          "bpm": "بی پی ایم",
          "date": "تاریخ",
          "time": "وقت",
          "searchForSpecialities": "ماہرین کی تلاش",
          "specialities": "خصوصیات",
          "consultNow": "آن لائن سے مشورہ کریں۔",
          "specialists": "ماہرین",
          "upcomingAppointments": "آنے والی ملاقاتیں",
          "dateAndTime": "تاریخ اور وقت",
          "reschedule": "ری شیڈول کریں۔",
          "onlineConsultation": "آن لائن مشاورت",
          "information1":
              "ہمارا سسٹم اور ایپس بنیادی طور پر ہیلتھ کیئر اور میڈیکل کو نشانہ بنا رہے ہیں۔ ",
          "information2":
              "مقام: قریبی ڈاکٹروں کو دکھانے کے لیے، ایپ کو صارف سے یہ اجازت لینا ہوگی۔ ",
          "usage":
              "ہم جو معلوماتی مواد جمع کرتے ہیں اسے ہم مختلف طریقوں سے استعمال کرتے ہیں، بشمول: (a) ہماری خدمات اور مصنوعات کو فراہم کرنا، چلانا، اور برقرار رکھنا (b) یہ سمجھنا اور تجزیہ کرنا کہ آپ ہماری خدمات اور مصنوعات کو کس طرح استعمال کرتے ہیں (c) نئی مصنوعات، خدمات کی خصوصیات کو تیار کرنا، اور ",
          "disclosure":
              "ہم کسی بھی شخص کے لیے ذاتی معلومات ظاہر کر سکتے ہیں جو ہمارے لیے آڈٹ، قانونی، آپریشنل یا دیگر خدمات انجام دے رہا ہو۔ ",
          "consent": "ہماری ویب سائٹ، خدمات کا استعمال کرتے ہوئے",
          "consentTitle": "رضامندی",
          "usageTitle": "استعمال",
          "disclosureTitle": "انکشاف",
          "informationWeCollect": "معلومات ہم جمع کرتے ہیں۔",
          "iHaveRead": "میں نے پڑھ کر سمجھ لیا ہے۔",
          "theTermsAndCondition": " شرائط و ضوابط",
          "accept": "قبول کریں۔",
          "decline": "رد کرنا",
          "height": "اونچائی",
          "weight": "وزن",
          "add": "شامل کریں۔",
          "servicesHome": "خدمات (گھر)",
          "teleConsultation": "ٹیلی کنسلٹیشن",
          "diagnostics": "تشخیص",
          "physio": "فزیو",
          "nursing": "نرسنگ",
          "caregiver": "دیکھ بھال کرنے والا",
          "respiratoryTherapy": "سانس کی تھراپی",
          "dietitian": "ماہر غذائیت",
          "serviceSelected": "سروس منتخب کر لی گئی۔",
          "collectesData":
              "سروس ہوم کو فعال کرنے کے لیے لوکیشن ڈیٹا اکٹھا کرتا ہے یہاں تک کہ جب بند ہو یا استعمال میں نہ ہو۔",
          "agree": "متفق",
          "appointmentNotes": "ملاقات کے نوٹس",
          "deny": "انکار کرنا",
          "search": "تلاش کریں۔",
          "homeVisit": "گھر کا دورہ",
          "online": "آن لائن",
          "subTotal": "ذیلی کل",
          "minFee": "کم از کم ",
          "doctorSchedule": "ڈاکٹر کا شیڈول",
          "fee": "فیس",
          "charges": "چارجز",
          "selectAddress": "پتہ منتخب کریں۔",
          "selectLocation": "مقام منتخب کریں۔",
          "goodMorning": "صبح بخیر",
          "token": "ٹوکن",
          "ecg": "ای سی جی",
          "selectLanguage": "زبان منتخب کریں۔",
          "english": "انگریزی",
          "arabic": "عربی",
          "hour": "گھنٹہ",
          "homeService": "ہوم کیئر سروس",
          "labInvestigationBooking": "لیب انویسٹی گیشن بکنگ",
          "experience": "تجربہ",
          "paying": "ادا کرنا",
          "serviceBooked": "سروس کامیابی کے ساتھ بک ہو گئی۔",
          "appointmentSuccessful": "ملاقات کامیابی کے ساتھ بک ہو گئی۔ ",
          "failedAppointment":
              "اپوائنٹمنٹ ناکام ہو گیا براہ کرم اپنا انٹرنیٹ کنکشن چیک کریں پھر دوبارہ کوشش کریں۔",
          "favorites": "پسندیدہ",
          "noFavorites": "کوئی پسندیدہ ڈاکٹر شامل نہیں کیا گیا۔",
          "contact": "رابطہ نمبر.",
          "province/state": "صوبہ/ریاست",
          "editProfile": "پروفائل میں ترمیم کریں",
          "update": "اپ ڈیٹ",
          "healthanalysis": "صحت کا تجزیہ",
          "herearesomehealth": "صحت کے بارے میں کچھ حقائق یہ ہیں۔ ",
          "men": "مرد",
          "In": "میں",
          "dubai": "دبئی، یو اے ای ",
          "doctorName": "ڈاکٹر کا نام",
          "careGivers": "دیکھ بھال کرنے والا",
          "disclaimer": "ڈس کلیمر",
          "services": "خدمات",
          "go": "جاؤ",
          "imaging": "امیجنگ بکنگ",
          "caretocure": "دیکھ بھال سے علاج تک",
          "forgotpassword": "پاسورڈ بھول گے ؟",
          "ithappens":
              "ایسا ہوتا ہے، برائے مہربانی اپنے اکاؤنٹ سے منسلک ای میل درج کریں۔",
          "createpassword": "نیا پاس ورڈ بنائیں",
          "kindlyenter": "براہ کرم ایک منفرد پاس ورڈ درج کریں۔",
          "oldpaasword": "پرانا پاسورڈ",
          "confirmpassword": "پاس ورڈ کی تصدیق کریں۔",
          "changepassword": "پاس ورڈ تبدیل کریں",
          "imagingTitle": "امیجنگ",
          "completed": "مکمل",
          "upcoming": "آنے والا",
          "cancelled": "منسوخ",
          "noDataFound": "کوئی ڈیٹا نہیں ملا!",
          "service": "سروس",
          "homeServices": "ہوم سروسز",
          "changePassword": "پاس ورڈ تبدیل کریں",
          "modeOfPayment": "ادائیگی کا طریقہ",
          "digitalPrescriptions": "ڈیجیٹل نسخے",
          "otherReports": "دیگر رپورٹس",
          "visitNo": "وزٹ نمبر",
          "checkInTime": "چیک ان ٹائم",
          "visitTime": "وزٹ ٹائم",
          "medicine": "دوائی",
          "dos": "DOS",
          "freq": "تعدد",
          "duration": "دورانیہ",
          "requested": "درخواست کی۔",
          "all": "تمام",
          "connectFamilyMember": "فیملی ممبر کو جوڑیں۔",
          "addFamilyMember": "فیملی ممبر شامل کریں۔",
          "personalInformation": "ذاتی معلومات",
          "firstName": "آخری نام",
          "fathersName": "باپ کا نام ",
          "phoneNumber": "فون نمبر",
          "relation": "رشتہ",
          "martialStatus": "ازدواجی حیثیت",
          "bloodGroup": "بلڈ گروپ",
          "relationShip": "رشتہ",
          "selectGender": "صنف منتخب کریں۔",
          "selectMartialStatus": "مارشل اسٹیٹس کو منتخب کریں۔",
          "selectBloodGroup": "بلڈ گروپ منتخب کریں۔",
          "firstNameRequired": "پہلا نام درکار ہے۔",
          "lastNameIsRequired": "آخری نام مطلوب ہے۔",
          "identityNumberIsRequired": "قومی شناختی کارڈ درکار ہے۔",
          "recordFound": "ریکارڈ ملا",
          "registrationDate": "داخلے کی تاریخ",
          "age": "عمر",
          "id": "ID",
          "documentsProof": "دستاویزات کا ثبوت",
          "report": "رپورٹ",
          "prescription": "نسخہ",
          "invoice": "رسید",
          "refund": "واپس کرنا",
          "amount": "رقم:",
          "addFamilyMembers": "فیملی ممبرز کو شامل کریں۔",
          "changeLocation": "مقام تبدیل کریں۔",
          "offline": "آف لائن",
          "atClinic": "گھر کا دورہ",
          "thisFieldIsRequired": "اس کو پر کرنا ضروری ہے",
          "doctorDidNotPrescribe": "ڈاکٹر نے ابھی تک کوئی دوائی تجویز نہیں کی۔",
          "noLabInvestigationsFound": "کوئی لیب کی تحقیقات نہیں ملی",
          "getTested": "ٹیسٹ کروائیں۔",
          "noDiagnostics": "ٹیسٹ کرنے کے لیے کوئی تشخیصی مواد دستیاب نہیں ہے۔",
          "year": "سال",
          "notifications": "اطلاعات",
          "norecordfound": "کوئی ریکارڈ نہیں ملا",
          "noservices": "کوئی خدمات منتخب نہیں ہیں۔",
          "noservicespackages": "کوئی خدمات یا پیکجز منتخب نہیں ہیں۔",
          "noaddress": "پتہ منتخب نہیں کیا گیا۔",
          "nopaymentmethod": "ادائیگی کا طریقہ منتخب نہیں کیا گیا۔",
          "thisdatetime": "یہ تاریخ اور وقت موجودہ وقت سے پہلے کا ہے۔ ",
          "bloodpressure": "بلڈ پریشر",
          "bloodpressuremoniter": "بلڈ پریشر مانیٹر",
          "servicealreadyselected": "سروس پہلے ہی منتخب ہے۔",
          "labtestalreadyselected": "لیب ٹیسٹ پہلے ہی منتخب ہے۔",
          "labtestpresent": "لیب ٹیسٹ پہلے سے ہی منتخب پیکجز میں موجود ہے۔",
          "pleasetryagain": "دوبارہ کوشش کریں",
          "bookingfailed": "بکنگ ناکام ہو گئی، براہ کرم دوبارہ کوشش کریں۔",
          "allrecordsfetched": "تمام ریکارڈ حاصل کر لیے گئے ہیں!",
          "labpackagealready": "لیب پیکیج پہلے ہی منتخب ہے۔",
          "someerroroccured": "کچھ خرابی پیش آگئی",
          "fillallfields":
              "تمام فیلڈز کو بھریں اور اپنی پروفائل تصویر شامل کریں۔",
          "passwordnotchanged": "پاس ورڈ تبدیل نہیں ہوا",
          "passandconfirmpass": "پاس ورڈ اور کنفرم پاس ورڈ مماثل نہیں ہیں۔",
          "youarenotloggedin": "آپ لاگ ان نہیں ہیں۔",
          "doctorofflice": "ڈاکٹر آف لائن ہے۔",
          "codesent": "کوڈ بھیج دیا گیا ہے۔",
          "somethingwentwrong": "کچھ غلط ہو گیا!",
          "passwordchanged": "پاس ورڈ تبدیل کر دیا گیا۔",
          "coderror": "کوڈ کی خرابی۔",
          "successfullyupdated": "کامیابی کے ساتھ اپ ڈیٹ",
          "failedtoupated": "اپ ڈیٹ کرنے میں ناکام ",
          "notfound": "نہیں ملا",
          "notestsselected": "کوئی ٹیسٹ منتخب نہیں کیا گیا۔",
          "pleaseloginfirst": "مہربانی فرما کر پہلے لاگ ان کریں",
          "samplesfromhome": "گھر سے نمونے۔",
          "samplesinlab": "لیب میں نمونے۔",
          "province": "صوبہ",
          "consultnow": "آن لائن سے مشورہ کریں۔",
          "homesampling": "ہوم سیمپلنگ",
          "selectdatetime": "تاریخ منتخب کریں۔",
          "selecttime": "وقت",
          "enterverificationcode": "تصدیقی کوڈ درج کریں",
          "entervericationsent":
              "تصدیقی کوڈ درج کریں اپنے ای میل یا فون نمبر پر بھیجیں۔",
          "confirm": "تصدیق کریں۔",
          "doctoriscalling": "ڈاکٹر بلا رہا ہے...",
          "waitingfordoctor": "ڈاکٹر کے انتظار میں...",
          "minutes": "منٹس",
          "estimatedtime": "متوقع وقت...",
          "patientname": "مریض کا نام",
          "patient": "صبر",
          "paymentmethod": "ادائیگی کا طریقہ",
          "scheduledappointment": "طے شدہ ملاقات",
          "patientinfo": "مریض کی معلومات",
          "paid": "ادا کیا",
          "yourrelation": "آپ کی حقیقت",
          "entercode": "کوڈ درج کریں",
          "kindlyenterthecode":
              "برائے مہربانی اپنے ای میل ایڈریس پر بھیجا گیا کوڈ درج کریں۔",
          "healthanalysistools": "صحت کے تجزیہ کے اوزار",
          "feet": "پاؤں",
          "inch": "انچ",
          "calculatebmi": "BMI کا حساب لگائیں۔",
          "weightkg": "وزن (کلوگرام)",
          "heightcm": "اونچائی (سینٹی میٹر)",
          "datetime": "تاریخ وقت",
          "high": "اعلی",
          "entersystolic": "سسٹولک / اپر بی پی درج کریں۔",
          "enterlowerbp": "سسٹولک / اپر بی پی درج کریں۔",
          "savebp": "بی پی کو بچائیں۔",
          "glucosemoniter": "گلوکوز لیول مانیٹر",
          "glocuselevel": "گلوکوز لیول",
          "systolicupper": "سسٹولک (اوپری)",
          "diastolic": "ڈائاسٹولک (نچلا)",
          "apptno": "ایپ نمبر",
          "report/desc": "رپورٹ/ نسخہ",
          "discount": "رعایت",
          "packagename": "پیکیج کا نام",
          "pdfnotavail": "PDF دستیاب نہیں ہے۔",
          "selectcountry": "براہ کرم ملک منتخب کریں۔",
          "selectprovince": "براہ کرم صوبہ منتخب کریں۔",
          "selectcity": "براہ کرم شہر کا انتخاب کریں۔",
          "echo": "بازگشت",
          "selectdate": "تاریخ منتخب کریں۔",
          "day": "دن",
          "sunday": "اتوار",
          "recenttrans": "حالیہ ٹرانزیکشنز",
          "onlineconsultancy": "آن لائن کنسلٹنسی",
          "loading": "لوڈ ہو رہا ہے...",
          "timer": "وقت",
          "nationalID": "اپنی قومی شناخت درج کریں۔",
          "comingsoon": "جلد آرہا ہے۔",
          "termsofuse": "استعمال کرنے کی شرائط",
          "link":
              "iHealthCure ویب سائٹ https://ihealthcure.com/ پر واقع ایک کاپی رائٹ کام ہے جو iHealthCure سے تعلق رکھتا ہے۔ ",
          "access": "سائٹ تک رسائی",
          "accessinformation": "ان شرائط کے تابع۔ ",
          "disclaimer1":
              "سائٹ \"جیسا ہے\" اور \"جیسا کہ دستیاب ہے\" کی بنیاد پر فراہم کی گئی ہے، اور کمپنی اور ہمارے سپلائرز کسی بھی قسم کی کسی بھی اور تمام وارنٹیوں اور شرائط کو واضح طور پر مسترد کرتے ہیں، چاہے وہ اظہار، مضمر، یا قانونی ہو، بشمول تمام وارنٹی یا تجارتی شرائط ",
          "disclaimertitle": "ڈس کلیمر",
          "contactinfo": "رابطے کی معلومات",
          "contactinfodetail": "پتہ: دفتر",
          "selectMaritalStatus": "ازدواجی حیثیت"
        }
      };
}
